# Generated by Django 4.1.5 on 2023-01-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_staffdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Datein', models.CharField(blank=True, max_length=30, null=True)),
                ('Dateout', models.CharField(blank=True, max_length=30, null=True)),
                ('Document', models.ImageField(blank=True, null=True, upload_to='customer')),
            ],
        ),
    ]
