# Generated by Django 4.1.4 on 2023-01-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_customerdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdb',
            old_name='Username',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='customerdb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
