# Generated by Django 4.1.5 on 2023-01-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rename_username_customerdb_name_customerdb_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.EmailField(blank=True, max_length=30, null=True)),
                ('Count', models.IntegerField(blank=True, null=True)),
                ('Price', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='room')),
            ],
        ),
    ]
