# Generated by Django 4.1.5 on 2023-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_roomdb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdb',
            name='Type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
