# Generated by Django 4.1.5 on 2023-01-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_roomdb_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindb',
            old_name='Username',
            new_name='Name',
        ),
    ]
