# Generated by Django 4.1.5 on 2023-01-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_rename_confirmpassword_staffdb_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomtypedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customerdb',
            old_name='Address',
            new_name='Room',
        ),
        migrations.RemoveField(
            model_name='customerdb',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='customerdb',
            name='Email',
        ),
    ]
