# Generated by Django 4.1.5 on 2023-01-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_roomtypedb_rename_address_customerdb_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtypedb',
            old_name='Name',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='roomtypedb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='room'),
        ),
    ]
