# Generated by Django 4.1.5 on 2023-01-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_rename_name_roomtypedb_description_roomtypedb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdb',
            name='Image',
        ),
    ]
