# Generated by Django 4.1.5 on 2023-01-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_remove_roomdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='room'),
        ),
    ]
