# Generated by Django 4.1.5 on 2023-01-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_roomdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdb',
            name='Image',
        ),
    ]
