# Generated by Django 4.1.5 on 2023-02-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_remove_roomdb_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staffdb',
        ),
    ]
