# Generated by Django 4.1.5 on 2023-02-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_delete_staffdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='roomsingle'),
        ),
    ]
