# Generated by Django 4.1.5 on 2023-02-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_roomdb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdb',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='roomsingle'),
        ),
        migrations.AddField(
            model_name='roomdb',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='roomsingle'),
        ),
    ]
